### ISSUE TITLE
Redis policy key goes to TTL = -1

### ISSUE THREAD

**Issue by vshah1975** [marcosbarbero/spring-cloud-zuul-ratelimit#311] opened 2020-03-06 04:07 UTC
I have a situation that comes up at least 2 - 3 times a day (with Ver 2.3, using embedded Redis 2.8.19) where the key that matches a policy will have TTL = -1 and therefore redis will not expire this key. 

I have not been to reproduce this condition manually.
![RateLimiter Redis TTL](https://user-images.githubusercontent.com/18020375/76050605-9e2ae600-5f2d-11ea-8fbb-fe890112bbda.png)

**Expected behavior**
They Key's TTL/Expires limit in redis should always be a positive number thereby expiring on its own.

**Environment & Versioning (please complete the following information):**
 - Ubuntu 18
 - Spring Boot Version: 2.1.7.RELEASE
 - Spring Cloud Version: 2.1.2.RELEASE
 - Spring Cloud Rate Limit Version: 2.3.0

**Additional context**

**Comment by vshah1975** [comment] 2020-03-06 16:50
An update: We were on ver 1.7.x for the past year and did not have this issue at all. However the upgrade to 2.2.x is where we are seeing this problem.

**Comment by marcosbarbero** [comment] 2020-03-07 21:07
Hi @vshah1975 what do you mean by Spring Cloud Version `2.1.2.RELEASE`? What's the release train?

Also, the Rate Limit Version `2.3.x` is not compatible with Spring Boot `2.1.x`, if you can't upgrade it to `2.2.x` it's better if you rollback it to the version `2.2.x`.

**Comment by vshah1975** [comment] 2020-03-07 22:46
we are using Greenwich.SR2 as the cloud release train.

We dont have an issue upgrading but will require a lot more testing. based on the bit of debugging that I have done, I am not sure the Spring Boot 2.2.x redistemplate implementation is any different than 2.1.x for ValueOperations.

**Comment by marcosbarbero** [comment] 2020-03-08 12:06
Hi @vshah1975 thanks for the feedback.

I'm not sure what are the changes from Spring Boot `2.1.x` to `2.2.x`, I do know there are not compatible, also the latest Spring Cloud (`Hoxton`) is only compatible with Spring Boot `2.2.x`, which makes this library (from the version `2.3.0`) also only compatible with Spring Cloud `Hoxton` and Spring Boot `2.2.x`.

It might not fix your problem indeed, but based on compatibilities I would advise you to upgrade your project's dependencies.

**Comment by hunterlodge** [comment] 2020-03-16 09:45
Hi marcosbarbero,

I observed the same thing as @vshah1975 when using Redis as the storage. The [TTL](https://redis.io/commands/ttl) of a key could be -1, which makes the rate limiting go wrong. After going through the code, I think I have found the cause.

The following code snippet comes from the class RedisRateLimiter in the jar spring-cloud-zuul-ratelimit-core-2.3.0.RELEASE.jar

` 66  Boolean present = redisTemplate.opsForValue().setIfAbsent(key, Long.toString(usage), refreshInterval.getSeconds(), SECONDS);
   67 if (Boolean.FALSE.equals(present)) {
   68   // Key already exists, increment
   69    current = redisTemplate.opsForValue().increment(key, usage);
   70 } else {
   71   current = usage;
   72 }`

I figured there could be some race condition between line 66 to line 69. Despite presence check at line 67, a new key with no expiration could be created at line 69 if the existing one just goes expired right between line 67 and line 69(The INCR operation 
 implicitly create a key if it doesn't exist). 

A TTL check and setting might be necessary after line 69 to make sure any key created has expiration

**Comment by marcosbarbero** [comment] 2020-03-16 09:53
Thanks @hunterlodge I'll fix it asap

**Comment by wzq1990413** [comment] 2020-04-16 03:11
I observed the same thing as @vshah1975 when using Redis as the storage in 2.4.0.RELEASE

**Comment by tunh** [comment] 2020-05-04 07:49
I have the same issue. I have to delete Redis key manually.

**Comment by tunh** [comment] 2020-05-27 02:40
Is there any update? I have the same issue with version 2.4.0

**Comment by marcosbarbero** [comment] 2020-06-01 10:10
@tunh sorry for the delay, this will be fixed at #348, just waiting for the code review.

**Closed** 2020-06-09 13:21 UTC
Labels: bug, status: feedback-provided

**Comment by marcosbarbero** [comment] 2020-06-09 16:11
Please check [v2.4.1.RELEASE](https://github.com/marcosbarbero/spring-cloud-zuul-ratelimit/releases/tag/v2.4.1.RELEASE)
